### ISSUE TITLE
when clicking on a category other categories unfold

### ISSUE THREAD

**Issue by nnyyxxxx** [hyprwm/hyprland-wiki#826]
so say i fold every category:
![image](https://github.com/user-attachments/assets/0af2811b-923d-4e85-b1c0-545e9b8bd6ae)
and then i decide i want to click on a category:
![image](https://github.com/user-attachments/assets/8d15c1bb-991f-4f39-9cba-e2ca5aecb007)
the two categories i folded previously: automatically unfold, this needs to be fixed ASAP

**Comment by vaxerski** [comment]
right repo.

**Comment by vaxerski** [comment]
> this needs to be fixed ASAP

this can't be fixed with our current theme, no? @fufexan 

especially not since we dont store any cookies. Unless I am unaware of something.

Also "ASAP" is a bit extreme.

**Comment by fufexan** [comment]
Yeah this should be fixed upstream, not something we control. Also this could be done with localStorage, no need for cookies.

**Comment by vaxerski** [comment]
right.

**Comment by fufexan** [comment]
This exact issue wasn't fixed, but at least the selected sidebar entry is now properly scrolled to. Hope that alleviates the problem a bit.

**Comment by nnyyxxxx** [comment]
> This exact issue wasn't fixed, but at least the selected sidebar entry is now properly scrolled to. Hope that alleviates the problem a bit.

feels buggy

**Comment by nnyyxxxx** [comment]
that is one terrible fix :joy:

**Comment by Bugg4** [comment]
This seems to happen because both `Getting started` and `Configuring` are set to be unfolded by default, with:
```yaml
sidebar:
  open: true
```
This would be fine if that was only valid on the main page: https://wiki.hypr.land/ and then decaded for inner directories.
The issue is that the `open: true` remains valid and is reapplied on each subsequent page load.

Imo, an acceptable workaround would be to start all categories collapsed by default. This would avoid the sidebar jumping around when navigating from category to category, so as too keep only the category of interest unfolded.

An ideal solution would be to store the either `open` or empty class for `<li>` category elements in localStorage.
